services:
  app:
    build: .
    container_name: fastrawgis-app
    volumes:
      - ./app:/code/app
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: postgis/postgis:16-3.5
    container_name: fastrawgis-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgis_data:/var/lib/postgresql/data/

volumes:
  postgis_data:
